export interface VerifiedEmergencyRecord {
  record_id: string;
  organisation_name: string;
  top_category: string;
  service_category: string;
  country: string; // "Nigeria" | "Ghana" | "United Kingdom" | "United States"
  countryCode: "NG" | "GH" | "GB" | "US";
  region: string;
  city: string;
  phone: string;
  whatsapp_or_text: string;
  email: string;
  service_summary: string;
  hours: string;
  cost: string;
  organisation_type: string;
  verification_status: string;
  obiren_follow_up: string;
  source_url: string;
}

export const VERIFIED_EMERGENCY_DATASET: VerifiedEmergencyRecord[] = [
  {
    record_id: "NG-001",
    organisation_name: "National Emergency Hotline",
    top_category: "Emergency services",
    service_category: "General emergency",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "",
    phone: "112",
    whatsapp_or_text: "",
    email: "",
    service_summary: "24/7 toll-free national emergency number for medical, fire, police and other emergencies.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Direct operational confirmation recommended",
    source_url: "https://www.nigerianmentalhealth.org/helplines"
  },
  {
    record_id: "NG-002",
    organisation_name: "Lagos State Emergency Services (LASEMA)",
    top_category: "Emergency services",
    service_category: "Disaster and medical emergency",
    country: "Nigeria",
    countryCode: "NG",
    region: "Lagos",
    city: "Lagos",
    phone: "112; 767",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Lagos State emergency response numbers.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Direct operational confirmation recommended",
    source_url: "https://lagosstate.gov.ng/"
  },
  {
    record_id: "NG-003",
    organisation_name: "FIDA Nigeria",
    top_category: "Legal and safety support",
    service_category: "Legal aid for women and children",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Abuja",
    phone: "+234 708 849 6115",
    whatsapp_or_text: "",
    email: "fidanigeria@yahoo.com",
    service_summary: "Legal assistance and advocacy for indigent women and children.",
    hours: "Contact provider",
    cost: "Free / nonprofit",
    organisation_type: "NGO",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm service hours and state branch coverage",
    source_url: "https://fida.org.ng/contacts/"
  },
  {
    record_id: "NG-004",
    organisation_name: "MSI Nigeria Reproductive Choices",
    top_category: "Women’s healthcare",
    service_category: "Sexual and reproductive health",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Abuja",
    phone: "0800 00 22252",
    whatsapp_or_text: "+234 909 902 2252",
    email: "info@mariestopes.org.ng",
    service_summary: "Family planning, contraception, pregnancy options and reproductive health support.",
    hours: "Contact provider",
    cost: "Contact provider",
    organisation_type: "NGO / healthcare",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm clinic-level addresses and hours before publishing",
    source_url: "https://www.msichoices.org/what-we-do/where-we-work/nigeria/"
  },
  {
    record_id: "NG-005",
    organisation_name: "She Writes Woman",
    top_category: "Mental health",
    service_category: "Mental health helpline and teletherapy",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Lagos",
    phone: "0800 800 2000",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Mental health support, teletherapy and rights-based advocacy.",
    hours: "24/7 helpline stated",
    cost: "Free helpline",
    organisation_type: "NGO",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm helpline availability before launch",
    source_url: "https://www.shewriteswoman.org/"
  },
  {
    record_id: "NG-006",
    organisation_name: "Project Alert on Violence Against Women",
    top_category: "Safety and abuse support",
    service_category: "Domestic and sexual violence support",
    country: "Nigeria",
    countryCode: "NG",
    region: "Lagos",
    city: "Lagos",
    phone: "0818 009 1072",
    whatsapp_or_text: "",
    email: "projectalert@projectalertnig.org",
    service_summary: "Counselling, advocacy, shelter referral and support for survivors of violence.",
    hours: "Contact provider",
    cost: "Nonprofit",
    organisation_type: "NGO",
    verification_status: "Directory source verified",
    obiren_follow_up: "Directly reconfirm phone and full address",
    source_url: "https://lagosdsva.org/service-directory-of-sgbv-providers/"
  },
  {
    record_id: "NG-007",
    organisation_name: "WARIF Centre",
    top_category: "Safety and abuse support",
    service_category: "Sexual assault and rape crisis support",
    country: "Nigeria",
    countryCode: "NG",
    region: "Lagos",
    city: "Lagos",
    phone: "0800 921 0009",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Medical, counselling and support services for survivors of sexual violence.",
    hours: "24/7 helpline stated",
    cost: "Free / nonprofit",
    organisation_type: "NGO",
    verification_status: "Directory source verified",
    obiren_follow_up: "Confirm current phone formatting and service location",
    source_url: "https://nomoredirectory.org/nigeria/"
  },
  {
    record_id: "NG-008",
    organisation_name: "Cece Yara Foundation Child Helpline",
    top_category: "Child protection",
    service_category: "Child abuse helpline",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Lagos",
    phone: "0800 800 8001",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Child protection and abuse response helpline.",
    hours: "24/7 stated by directory",
    cost: "Free",
    organisation_type: "NGO",
    verification_status: "Directory source verified",
    obiren_follow_up: "Directly reconfirm before launch",
    source_url: "https://nomoredirectory.org/nigeria/"
  },
  {
    record_id: "NG-009",
    organisation_name: "Federal Girls and Women Violation Toll-Free Line",
    top_category: "Safety and abuse support",
    service_category: "Gender-based violence reporting",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Abuja",
    phone: "0800 72 73 2255",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Federal toll-free line for violations against girls and women.",
    hours: "Contact provider",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Directory source verified",
    obiren_follow_up: "Confirm responsible agency and operating hours",
    source_url: "https://nomoredirectory.org/nigeria/"
  },
  {
    record_id: "NG-010",
    organisation_name: "Lagos State Domestic and Sexual Violence Agency Service Directory",
    top_category: "Safety and abuse support",
    service_category: "SGBV provider referral directory",
    country: "Nigeria",
    countryCode: "NG",
    region: "Lagos",
    city: "Lagos",
    phone: "0800 333 3333",
    whatsapp_or_text: "",
    email: "dsva@lagosstate.gov.ng",
    service_summary: "Directory of sexual and gender-based violence service providers in Lagos.",
    hours: "Online",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Use as a source for provider-level ingestion",
    source_url: "https://lagosdsva.org/service-directory-of-sgbv-providers/"
  },
  {
    record_id: "NG-011",
    organisation_name: "Lagos State Secondary Health Facilities",
    top_category: "Hospitals and maternity",
    service_category: "Public hospitals and maternal-child centres",
    country: "Nigeria",
    countryCode: "NG",
    region: "Lagos",
    city: "Lagos",
    phone: "0800 000 1111",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Official directory of Lagos State general hospitals and maternal and child care centres.",
    hours: "Varies",
    cost: "Public healthcare",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Ingest individual facilities separately with direct checks",
    source_url: "https://lagosministryofhealth.org/secondary-health-facilities/"
  },
  {
    record_id: "NG-012",
    organisation_name: "National Human Rights Commission Nigeria",
    top_category: "Legal and safety support",
    service_category: "Human-rights complaints and GBV advocacy",
    country: "Nigeria",
    countryCode: "NG",
    region: "Nationwide",
    city: "Abuja",
    phone: "+234 9 290 4708",
    whatsapp_or_text: "",
    email: "info@nigeriarights.gov.ng",
    service_summary: "Human-rights complaints, advocacy and referrals, including sexual and gender-based violence.",
    hours: "Contact provider",
    cost: "Government service",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Add direct contact after official confirmation",
    source_url: "https://www.nigeriarights.gov.ng/"
  },
  {
    record_id: "GH-001",
    organisation_name: "Ghana Emergency Response Centre",
    top_category: "Emergency services",
    service_category: "General emergency",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "112",
    whatsapp_or_text: "",
    email: "",
    service_summary: "General national emergency response number.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Operational confirmation recommended",
    source_url: "https://www.mint.gov.gh/"
  },
  {
    record_id: "GH-002",
    organisation_name: "Ghana Police Service",
    top_category: "Emergency services",
    service_category: "Police emergency",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "191; 18555",
    whatsapp_or_text: "",
    email: "support@police.gov.gh",
    service_summary: "Police emergency and public safety support.",
    hours: "24/7 emergency",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm network availability for 18555",
    source_url: "https://www.mint.gov.gh/agencies/ghana-police-service/"
  },
  {
    record_id: "GH-003",
    organisation_name: "Ghana National Fire Service",
    top_category: "Emergency services",
    service_category: "Fire and rescue",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "192; 0299340383",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Fire and rescue emergency response.",
    hours: "24/7 emergency",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Operational confirmation recommended",
    source_url: "https://www.mint.gov.gh/agencies/ghana-national-fire-service/"
  },
  {
    record_id: "GH-004",
    organisation_name: "Ghana National Ambulance Service",
    top_category: "Emergency services",
    service_category: "Ambulance and pre-hospital care",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "112; 193",
    whatsapp_or_text: "",
    email: "",
    service_summary: "National ambulance and pre-hospital emergency medical response.",
    hours: "24/7",
    cost: "Free emergency line",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm whether 193 remains active alongside 112",
    source_url: "https://nas.gov.gh/"
  },
  {
    record_id: "GH-005",
    organisation_name: "National Disaster Management Organisation",
    top_category: "Emergency services",
    service_category: "Disaster management",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "0299350030",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Disaster response and management service.",
    hours: "24/7 emergency context",
    cost: "Government service",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Directly reconfirm hotline",
    source_url: "https://www.mint.gov.gh/"
  },
  {
    record_id: "GH-006",
    organisation_name: "Domestic Violence and Victim Support Unit (DOVVSU)",
    top_category: "Safety and abuse support",
    service_category: "Domestic violence and victim support",
    country: "Ghana",
    countryCode: "GH",
    region: "Nationwide",
    city: "Accra",
    phone: "+233 30 277 3906",
    whatsapp_or_text: "",
    email: "dovvsu@police.gov.gh",
    service_summary: "Police unit supporting victims of domestic violence, abuse and related offences.",
    hours: "Contact provider",
    cost: "Government service",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "Add national and regional office contacts after direct verification",
    source_url: "https://police.gov.gh/en/index.php/domestic-violence-victims-support-unit-dovvsu/"
  },
  {
    record_id: "GH-007",
    organisation_name: "Ghana Police Hospital",
    top_category: "Hospitals and urgent care",
    service_category: "Hospital and police medical services",
    country: "Ghana",
    countryCode: "GH",
    region: "Greater Accra",
    city: "Accra",
    phone: "+233 30 277 7595",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Hospital providing medical services in Accra.",
    hours: "Varies",
    cost: "Contact provider",
    organisation_type: "Government hospital",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm public eligibility, emergency contacts and address",
    source_url: "https://police.gov.gh/en/index.php/police-hospital-accra/"
  },
  {
    record_id: "GB-001",
    organisation_name: "United Kingdom Emergency Services",
    top_category: "Emergency services",
    service_category: "Police, ambulance and fire",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Nationwide",
    city: "London",
    phone: "999",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Immediate emergency response for danger to life or serious incidents.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.gov.uk/guidance/domestic-abuse-how-to-get-help"
  },
  {
    record_id: "GB-002",
    organisation_name: "NHS 111",
    top_category: "Urgent healthcare",
    service_category: "Urgent medical and mental health support",
    country: "United Kingdom",
    countryCode: "GB",
    region: "England",
    city: "London",
    phone: "111",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Urgent healthcare advice and direction to appropriate services; mental health support is available through 111.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Public healthcare",
    verification_status: "Source verified",
    obiren_follow_up: "Country variants required for Scotland, Wales and Northern Ireland",
    source_url: "https://www.nhs.uk/nhs-services/urgent-and-emergency-care-services/when-to-use-111/"
  },
  {
    record_id: "GB-003",
    organisation_name: "National Domestic Abuse Helpline — Refuge",
    top_category: "Safety and abuse support",
    service_category: "Domestic abuse helpline",
    country: "United Kingdom",
    countryCode: "GB",
    region: "England",
    city: "London",
    phone: "0808 2000 247",
    whatsapp_or_text: "",
    email: "helpline@refuge.org.uk",
    service_summary: "Free confidential support and refuge referral for women experiencing domestic abuse.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Charity",
    verification_status: "Source verified",
    obiren_follow_up: "Primarily England; add nation-specific services separately",
    source_url: "https://www.gov.uk/government/news/refuge-awarded-grant-to-operate-domestic-abuse-helpline"
  },
  {
    record_id: "GB-004",
    organisation_name: "24/7 Rape and Sexual Abuse Support Line",
    top_category: "Sexual violence support",
    service_category: "Rape and sexual abuse helpline",
    country: "United Kingdom",
    countryCode: "GB",
    region: "England and Wales",
    city: "London",
    phone: "0808 500 2222",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Free confidential emotional support for people aged 16+ affected by sexual violence or abuse.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Commissioned support service",
    verification_status: "Source verified",
    obiren_follow_up: "Add webchat availability in app record",
    source_url: "https://www.gov.uk/guidance/support-for-victims-of-sexual-violence-and-abuse"
  },
  {
    record_id: "GB-005",
    organisation_name: "MSI Reproductive Choices UK",
    top_category: "Women’s healthcare",
    service_category: "Sexual and reproductive healthcare",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Nationwide",
    city: "London",
    phone: "0345 300 8090",
    whatsapp_or_text: "",
    email: "services@msichoices.org.uk",
    service_summary: "NHS and private reproductive healthcare, contraception and pregnancy-options support.",
    hours: "Contact provider",
    cost: "NHS / private",
    organisation_type: "Healthcare provider",
    verification_status: "Source verified",
    obiren_follow_up: "Add clinic locations separately",
    source_url: "https://www.msichoices.org.uk/"
  },
  {
    record_id: "US-001",
    organisation_name: "United States Emergency Services",
    top_category: "Emergency services",
    service_category: "Police, ambulance and fire",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "Washington DC",
    phone: "911",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Immediate emergency response.",
    hours: "24/7",
    cost: "Free emergency call",
    organisation_type: "Government",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.911.gov/"
  },
  {
    record_id: "US-002",
    organisation_name: "988 Suicide & Crisis Lifeline",
    top_category: "Mental health",
    service_category: "Suicide and crisis support",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "988",
    whatsapp_or_text: "Text 988",
    email: "",
    service_summary: "Free confidential crisis support by call, text or chat.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Federally supported network",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.samhsa.gov/find-help/988"
  },
  {
    record_id: "US-003",
    organisation_name: "National Domestic Violence Hotline",
    top_category: "Safety and abuse support",
    service_category: "Domestic violence helpline",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "Austin",
    phone: "1-800-799-7233",
    whatsapp_or_text: "Text START to 88788",
    email: "",
    service_summary: "Confidential domestic violence support and connection to local services.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Nonprofit hotline",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.justice.gov/ovw/resources-victims-and-survivors"
  },
  {
    record_id: "US-004",
    organisation_name: "National Sexual Assault Hotline",
    top_category: "Sexual violence support",
    service_category: "Sexual assault helpline",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-800-656-4673",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Confidential sexual assault support and local referrals.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Nonprofit hotline",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.justice.gov/ovw/resources-victims-and-survivors"
  },
  {
    record_id: "US-005",
    organisation_name: "National Maternal Mental Health Hotline",
    top_category: "Pregnancy and maternity",
    service_category: "Maternal mental health support",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-833-852-6262",
    whatsapp_or_text: "Text 1-833-852-6262",
    email: "",
    service_summary: "Free confidential support for pregnant and postpartum people and their families in English and Spanish.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Federal hotline",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://mchb.hrsa.gov/programs-impact/national-maternal-mental-health-hotline"
  },
  {
    record_id: "US-006",
    organisation_name: "National Human Trafficking Hotline",
    top_category: "Safety and abuse support",
    service_category: "Human trafficking support",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-888-373-7888",
    whatsapp_or_text: "Text 233733",
    email: "",
    service_summary: "Confidential support, reporting and connection to local services.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "National hotline",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://ovc.ojp.gov/help-for-victims/toll-free-text-and-online-hotlines"
  },
  {
    record_id: "US-007",
    organisation_name: "Poison Control",
    top_category: "Emergency healthcare",
    service_category: "Poisoning and medication emergency",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-800-222-1222",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Immediate treatment advice for poisonings and poison-prevention questions.",
    hours: "24/7",
    cost: "Free",
    organisation_type: "Poison control network",
    verification_status: "Source verified",
    obiren_follow_up: "None",
    source_url: "https://www.poisonhelp.org/"
  },
  {
    record_id: "US-008",
    organisation_name: "VictimConnect Resource Center",
    top_category: "Legal and victim support",
    service_category: "Crime victim support and referral",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-855-484-2846",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Confidential referrals and information for victims of crime.",
    hours: "Contact provider",
    cost: "Free",
    organisation_type: "National resource centre",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm current chat/text options",
    source_url: "https://www.justice.gov/ovw/resources-victims-and-survivors"
  },
  {
    record_id: "US-009",
    organisation_name: "StrongHearts Native Helpline",
    top_category: "Safety and abuse support",
    service_category: "Domestic and sexual violence support for Native Americans",
    country: "United States",
    countryCode: "US",
    region: "Nationwide",
    city: "",
    phone: "1-844-762-8483",
    whatsapp_or_text: "",
    email: "",
    service_summary: "Culturally appropriate support for Native Americans and Alaska Natives affected by domestic and sexual violence.",
    hours: "24/7 stated by federal directory",
    cost: "Free",
    organisation_type: "Nonprofit hotline",
    verification_status: "Source verified",
    obiren_follow_up: "Confirm current operating details",
    source_url: "https://www.justice.gov/ovw/resources-victims-and-survivors"
  }
];
